user:
  name_max_length: 50
  email_max_length: 255
  password_min_length: 6
  hour_expire: 2
sessions:
  check_session: "1"
helpers:
  users_helper:
    size: 80
users:
  gravatar:
    size: 50
users_per_page: 15
posts_per_page: 15
content_max_size: 140
gravatar_post_size: 50
img_max_size: 5
type_img: "image/jpeg,image/gif,image/png"
